spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: false
  datasource:
    url: "jdbc:mysql://localhost:3306/memes_db"
    username: "memes_user"
    password: ${DB_PWD}

